### ISSUE TITLE
Position items relative to the container element's content

### ISSUE THREAD

**Issue by niklasramo** [haltu/muuri#22]
The gutter between the items is fully controlled via CSS, so if you wanted to have a gutter of 1px between the items you would probably do something like this:

```css
.grid {
  border-right: 1px solid transparent;
  border-bottom: 1px solid transparent;
}
.item {
  margin: 1px 0 0 1px;
}
```

If we would give padding to the grid element it would do us no good since absolute positioned elements are always positioned relative to the outer edge of the containing element's padding. So using border is needed here. The problem is, however, that if we wanted the grid to have a visual border we would need wrap it in another element.

So, to overcome this annoyance I think the padding could be made useful by making the item elements position themselves relative to the inner edge of the containing element's padding. This way the CSS could be written like this:

```css
.grid {
  padding: 0 1px 1px 0;
}
.item {
  margin: 1px 0 0 1px;
}
```

And we could also use border for other purposes on the grid element :)
