### ISSUE TITLE
Stacked grids are overlapping on page resize v0.8.0

### ISSUE THREAD

**Issue by JosephScript** [haltu/muuri#336]
Here's an example I have on my site which worked in v0.7:

```html
<div class="grid">
  <div class="item item-1">
Quia id commodi sint tenetur omnis exercitationem deleniti. Vel ullam nesciunt nostrum mollitia. Quisquam aspernatur laudantium molestias blanditiis.

Vel aut aliquam commodi aut odio voluptas. Eos maiores inventore debitis corrupti aut atque deserunt. Non qui excepturi odio et ut. Laudantium vel temporibus cum accusantium explicabo soluta placeat.

Fuga et odio sit sed et quaerat. Vero quidem ut a. Vel corrupti sed dicta.

Officiis totam reprehenderit aliquid adipisci. Dolorem minima quia repudiandae consequatur laboriosam dolores consequatur commodi. Consequatur rerum ipsum omnis aut id et sapiente. Ipsam aperiam et et sapiente.

Consequatur totam aut excepturi optio ex non non aut. Est et consequatur corrupti vitae. Impedit necessitatibus nostrum rerum quo vitae facere.

  </div>
</div>
<div class="grid">
  <div class="item item-2">
    Item 2
  </div>
  <div class="item item-3">
    Item 3
  </div>
</div>
```

```css
.grid {
  position: relative;
  margin: 16px -8px;
}
.item {
  display: block;
  position: absolute;
  margin: 0 8px 8px 8px;
  z-index: 0;
}
.item-1 {
  background: tomato;
  width: 100%;
}
.item-2 {
  background: PeachPuff ;
  width: 50%;
}
.item-3 {
  background: rebeccapurple;
  width: 50%;
}
```

```js
import Muuri from 'muuri';

const grid = new Muuri('.grid', {
  layout: {
    rounding: false
  }
})
```

The two grids show up fine where they should be, but when I resize the page and the elements move around, the grids overlap. 

Thanks for any help!
